### PR TITLE
Added wrapping of capture stream for DoubleBufferVideoProcessor

### PR DESCRIPTION
**Pull request by erikhagglund**
Changed so that the wrapper creates own capture stream and use it towards HAL instead of simply passing the capture stream from the framework

### CODE REVIEW

**Comment by thomasfanell** [comment]
Since we're obviously using C++11, why not replace `NULL` with `nullptr`?

**Comment by emilwestergren** [comment]
We changed to C++11 recently, so we still have lots of things to adapt. Should at least use `nullptr` in new code though.

**Comment by erikhagglund** [comment]
I have changed NULL to nullptr

**Comment by emilwestergren** [comment]
Recreate the PR and merge it to `develop` branch instead.

**Pull request closed without merging**
