### PR TITLE
added usage for graphic buffer lock.

### PR DESCRIPTION
**Pull request by ziquanyu**
added usage for graphic buffer lock.

### CODE REVIEW

**Comment by ziquanyu** [comment]
@davidhesselbom this should be merged too, you have merged the corresponding one in kean but not this one, it will not compile.

**Comment by davidhesselbom** [comment]
Please add a link to the one in ooc-kean in this one's description.

**Comment by davidhesselbom** [comment]
It actually works fine for me without this fix, both compiling and running. What am I missing?

**Comment by davidhesselbom** [comment]
Btw, I think @emilwestergren is the one responsible for merging pull requests in this repo...

**Comment by ziquanyu** [comment]
@davidhesselbom okay, maybe it will run, but it's not correctly running.  https://github.com/ziquanyu/ooc-kean/commit/403c9d4df48878860d4c742dc0da05da35de7ccf

**Comment by davidhesselbom** [comment]
Fine, but it won't affect anyone until they update the wrapper in their phone, right?

**Comment by ziquanyu** [comment]
It will affect if anyone update only kean and run it on the phone with old wrapper. 
It may not crush but it will cause wired result, because the flags to the GraphicBuffer are not matched between kean and wrapper.

**Comment by davidhesselbom** [comment]
In that case, either I revert your PR in ooc-kean, or @emilwestergren merges this.

**Comment by ziquanyu** [comment]
okay, thanks

**Pull request merged**
