### PR TITLE
Removed code modifying settings since they do not work properly anyway.

### PR DESCRIPTION
**Pull request by emilwestergren**
@sebastianbaginski peer review

### CODE REVIEW

**Comment by sebastianbaginski** [comment]
Should we remove them or fix ?

**Comment by emilwestergren** [comment]
They need to be fixed in vidproc and that might take a while so I thought it's better to remove them for now.

**Comment by sebastianbaginski** [comment]
Alright

**Comment by sebastianbaginski** [comment]
Ops sorry bad flag

**Comment by emilwestergren** [comment]
Haha, yes we don't have those fancy flags in here :)

**Pull request merged**
