### PR TITLE
added settings for contrast in wrapper.

### PR DESCRIPTION
**Pull request by ziquanyu**
Added contrast settings in wrapper.

### CODE REVIEW

**Comment by ziquanyu** [comment]
@emilwestergren Can you help to review this? Thanks!
I saw they added other settings too. It might be better to have put in all settings now. What do you think?

**Comment by emilwestergren** [comment]
I reverted this since it's not merged yet in Vidproc, so you have to redo it.

**Comment by ziquanyu** [comment]
you mean create PR again?

**Comment by marcusnaslund** [comment]
The changes have now been merged into vidproc.

**Comment by emilwestergren** [comment]
Yes

**Pull request merged**
